### ISSUE TITLE
test_bufr_python_mpi_test fails for me

### ISSUE THREAD

**Issue by DJDavies2** [rmclaren/bufr-query#42]
Running test_bufr_python_mpi_test results in this failure for me:

PRE-MAIN-INFOPRE-MAIN-INFO MPI task: 1 Parser Finished [0.04s]
 Encoder Finished [0.063s]
DIFFER : VARIABLE : sensorViewAngle : POSITION : [150] : VALUES : -25.617 <> -24.367
DIFFER : VARIABLE : sensorViewAngle : POSITION : [151] : VALUES : -25.617 <> -24.367
DIFFER : VARIABLE : sensorViewAngle : POSITION : [240] : VALUES : 24.393 <> 25.643
DIFFER : VARIABLE : sensorViewAngle : POSITION : [241] : VALUES : 24.393 <> 25.643
Variable        Group     Count Sum AbsSum   Min   Max Range  Mean StdDev
sensorViewAngle /MetaData     4  -5      5 -1.25 -1.25     0 -1.25      0
Traceback (most recent call last):
  File "/data/users/david.davies/cylc-run/mi-bg671/work/1/build_bufr_query_gnu/build/test/testinput/bufrtest_python_mpi_test.py", line 86, in <module>
    test_mpi_categories()
  File "/data/users/david.davies/cylc-run/mi-bg671/work/1/build_bufr_query_gnu/build/test/testinput/bufrtest_python_mpi_test.py", line 46, in test_mpi_categories
    run_compare('testrun/bufrtest_mtiasi_metop-c_cats.nc', COMP_PATH)
  File "/data/users/david.davies/cylc-run/mi-bg671/work/1/build_bufr_query_gnu/build/test/testinput/bufrtest_python_mpi_test.py", line 12, in run_compare
    assert result == 0, f"Comparison failed for {input_path} and {comp_path}."
AssertionError: Comparison failed for testrun/bufrtest_mtiasi_metop-c_cats.nc and testoutput/bufrtest_mtiasi_metop-c.nc.

Is this test supposed to work?

I am using gcc 9, mpich 4.2.3

**Comment by rmclaren** [comment]
This failure is currently expected, sorry for the confusion I should just comment out that test...

**Comment by rmclaren** [comment]
Related to #26.

**Comment by DJDavies2** [comment]
Thanks, I commented it out.

**Comment by rmclaren** [comment]
Fixed with updated unit test data stored in the RZDM ftp server
